### ISSUE TITLE
Operands don't affect result

### ISSUE THREAD

**Issue by okashany** [openbmc/libmctp#10]
astlpc.c line #997:
assert(astlpc->binding.pkt_size >= 0);
astlpc->binding.pkt_size >= 0 is always true (size_t) regardless of the values of its operands.

**Comment by amboar** [comment]
Okay, guessing slight with this one too, that it's in-fact referencing the following:

https://github.com/openbmc/libmctp/blob/f447b4f440929eb773d458fbf5242ed558f9f936/astlpc.c#L991

When filing bugs, please make sure to mention the most recent commit at which you found the problem (and that it is in-fact a commit that exists in upstream, i.e. this repository).

The assert condition would have been affected by the change in e889b19f4b349cd5c4ff186ff3c3b604c8f9c7b6.

Based on what it's protecting, I think we can delete the assertion and cast body to size_t for the subsequent comparison.

**Comment by amboar** [comment]
https://gerrit.openbmc.org/c/openbmc/libmctp/+/58678
